/*
 * Source: ArConsultarCaller.java - Generated by OBCOM SQL Wizard 5.1.266
 * Author: Felipe Gonzalez M (DP S.A.)
 *
 * Copyright (c) OBCOM INGENIERIA S.A. (Chile). All rights reserved.
 *
 * All rights to this product are owned by OBCOM INGENIERIA S.A. and may only be
 * used  under  the  terms of its associated license document. You may NOT copy,
 * modify, sublicense, or distribute this source file or portions of  it  unless
 * previously  authorized in writing by OBCOM INGENIERIA S.A. In any event, this
 * notice and above copyright must always be included verbatim with this file.
 */

package cl.teso.reca.pkgcajaservicestrx;

import java.math.BigDecimal;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.sql.DataSource;
import javax.sql.RowSet;

/**
 * Implements a caller of procedure "RECA.PKG_CAJA_SERVICES_TRX.AR_CONSULTAR".
 * <pre>
 * IN_CODIGO_BARRA    VARCHAR2(4000)     Input
 * IN_FOLIO_AR        NUMBER             Input
 * OUT_AR_DATA        REF CURSOR         Output
 * </pre>
 */
public class ArConsultarCaller extends ProcedureCaller
{
    /**
     * Executes procedure "RECA.PKG_CAJA_SERVICES_TRX.AR_CONSULTAR" using a DataSource.
     */
    public static ArConsultarResult execute(DataSource dataSource, String inCodigoBarra, BigDecimal inFolioAr)
        throws SQLException
    {
        Connection conn = dataSource.getConnection();
        try {
            return execute(conn, inCodigoBarra, inFolioAr);
        } finally {
            conn.close();
        }
    }

    /**
     * Executes procedure "RECA.PKG_CAJA_SERVICES_TRX.AR_CONSULTAR" using a Connection.
     */
    public static ArConsultarResult execute(Connection conn, String inCodigoBarra, BigDecimal inFolioAr)
        throws SQLException
    {
        ArConsultarResult result = new ArConsultarResult();
        ArrayList resultSets = new ArrayList();
        if (conn.getMetaData().getURL().startsWith("jdbc:oracle:")) {
            CallableStatement call = conn.prepareCall("{call RECA.PKG_CAJA_SERVICES_TRX.AR_CONSULTAR(?,?,?)}");
            try {
                call.setString(1, inCodigoBarra);
                call.setBigDecimal(2, inFolioAr);
                call.registerOutParameter(3, ORACLE_CURSOR);
                call.execute();
                resultSets.add(toRowSet((ResultSet)call.getObject(3)));
            } finally {
                call.close();
            }
        } else {
            CallableStatement call = conn.prepareCall("{call RECA.PKG_CAJA_SERVICES_TRX.AR_CONSULTAR(?,?)}");
            try {
                call.setString(1, inCodigoBarra);
                call.setBigDecimal(2, inFolioAr);
                int updateCount = 0;
                boolean haveRset = call.execute();
                while (haveRset || updateCount != -1) {
                    if (!haveRset)
                        updateCount = call.getUpdateCount();
                    else
                        resultSets.add(toRowSet(call.getResultSet()));
                    haveRset = call.getMoreResults();
                }
            } finally {
                call.close();
            }
        }
        if (resultSets.size() > 0) {
            RowSet[] rowSets = new RowSet[resultSets.size()];
            result.setRowSets((RowSet[]) resultSets.toArray(rowSets));
        }
        return result;
    }
}
