/*
 * Source: ArIngresarResult.java - Generated by OBCOM SQL Wizard 5.1.266
 * Author: Felipe Gonzalez M (DP S.A.)
 *
 * Copyright (c) OBCOM INGENIERIA S.A. (Chile). All rights reserved.
 *
 * All rights to this product are owned by OBCOM INGENIERIA S.A. and may only be
 * used  under  the  terms of its associated license document. You may NOT copy,
 * modify, sublicense, or distribute this source file or portions of  it  unless
 * previously  authorized in writing by OBCOM INGENIERIA S.A. In any event, this
 * notice and above copyright must always be included verbatim with this file.
 */

package cl.teso.reca.pkgcajaservicestrx;

import java.math.BigDecimal;
import javax.sql.RowSet;

/**
 * Output parameters of procedure "RECA.PKG_CAJA_SERVICES_TRX.AR_INGRESAR".
 */
public class ArIngresarResult extends ProcedureResult
{
    private static final long serialVersionUID = 1L;
    private String outCodigoBarra;
    private BigDecimal outFolioAr;
    private RowSet[] rowSets;

    /**
     * Constructor.
     */
    public ArIngresarResult()
    {
        super();
    }

    /**
     * Returns the value of "OutCodigoBarra".
     */
    public String getOutCodigoBarra()
    {
        return outCodigoBarra;
    }

    /**
     * Changes the value of "OutCodigoBarra".
     */
    public void setOutCodigoBarra(String outCodigoBarra)
    {
        this.outCodigoBarra = outCodigoBarra;
    }

    /**
     * Returns the value of "OutFolioAr".
     */
    public BigDecimal getOutFolioAr()
    {
        return outFolioAr;
    }

    /**
     * Changes the value of "OutFolioAr".
     */
    public void setOutFolioAr(BigDecimal outFolioAr)
    {
        this.outFolioAr = outFolioAr;
    }

    /**
     * Changes the value of "RowSets".
     */
    void setRowSets(RowSet[] rowSets)
    {
        this.rowSets = rowSets;
    }

    /**
     * Returns the value of "RowSetCount".
     */
    public int getRowSetCount()
    {
        return (rowSets != null) ? rowSets.length : 0;
    }

    /**
     * Returns the "RowSet" at the specified index.
     */
    public RowSet getRowSet(int index)
    {
        if (index < 0 || index >= getRowSetCount())
            throw new ArrayIndexOutOfBoundsException(index);
        return rowSets[index];
    }
}
