/*
 * Source: ConsultaDeudaCajaRsCaller.java - Generated by OBCOM SQL Wizard 5.1.266
 * Author: Felipe Gonzalez M (DP S.A.)
 *
 * Copyright (c) OBCOM INGENIERIA S.A. (Chile). All rights reserved.
 *
 * All rights to this product are owned by OBCOM INGENIERIA S.A. and may only be
 * used  under  the  terms of its associated license document. You may NOT copy,
 * modify, sublicense, or distribute this source file or portions of  it  unless
 * previously  authorized in writing by OBCOM INGENIERIA S.A. In any event, this
 * notice and above copyright must always be included verbatim with this file.
 */

package cl.teso.reca.pkgcajaservicestrx;

import java.math.BigDecimal;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Types;
import java.util.ArrayList;
import java.util.Date;
import javax.sql.DataSource;
import javax.sql.RowSet;

/**
 * Implements a caller of procedure "RECA.PKG_CAJA_SERVICES_TRX.CONSULTA_DEUDA_CAJA_RS".
 * <pre>
 * IN_CLIENTE_TIPO    NUMBER             Input
 * IN_RUT_ROL         NUMBER             Input
 * IN_RUT_ROL_DV      CHAR(2000)         Input
 * IN_FORM_COD        NUMBER             Input
 * IN_FORM_VER        CHAR(2000)         Input
 * IN_FORM_FOLIO      NUMBER             Input
 * IN_FECHA_VCTO      DATE               Input
 * IN_PERIODO         DATE               Input
 * OUT_ERRLVL         NUMBER             Output
 * CURSOR_RET         REF CURSOR         Output
 * </pre>
 */
public class ConsultaDeudaCajaRsCaller extends ProcedureCaller
{
    /**
     * Executes procedure "RECA.PKG_CAJA_SERVICES_TRX.CONSULTA_DEUDA_CAJA_RS" using a DataSource.
     */
    public static ConsultaDeudaCajaRsResult execute(DataSource dataSource, BigDecimal inClienteTipo, BigDecimal inRutRol, String inRutRolDv, BigDecimal inFormCod, String inFormVer, BigDecimal inFormFolio, Date inFechaVcto, Date inPeriodo)
        throws SQLException
    {
        Connection conn = dataSource.getConnection();
        try {
            return execute(conn, inClienteTipo, inRutRol, inRutRolDv, inFormCod, inFormVer, inFormFolio, inFechaVcto, inPeriodo);
        } finally {
            conn.close();
        }
    }

    /**
     * Executes procedure "RECA.PKG_CAJA_SERVICES_TRX.CONSULTA_DEUDA_CAJA_RS" using a Connection.
     */
    public static ConsultaDeudaCajaRsResult execute(Connection conn, BigDecimal inClienteTipo, BigDecimal inRutRol, String inRutRolDv, BigDecimal inFormCod, String inFormVer, BigDecimal inFormFolio, Date inFechaVcto, Date inPeriodo)
        throws SQLException
    {
        ConsultaDeudaCajaRsResult result = new ConsultaDeudaCajaRsResult();
        ArrayList resultSets = new ArrayList();
        if (conn.getMetaData().getURL().startsWith("jdbc:oracle:")) {
            CallableStatement call = conn.prepareCall("{call RECA.PKG_CAJA_SERVICES_TRX.CONSULTA_DEUDA_CAJA_RS(?,?,?,?,?,?,?,?,?,?)}");
            try {
                call.setBigDecimal(1, inClienteTipo);
                call.setBigDecimal(2, inRutRol);
                call.setString(3, inRutRolDv);
                call.setBigDecimal(4, inFormCod);
                call.setString(5, inFormVer);
                call.setBigDecimal(6, inFormFolio);
                call.setTimestamp(7, toTimestamp(inFechaVcto));
                call.setTimestamp(8, toTimestamp(inPeriodo));
                call.registerOutParameter(9, Types.NUMERIC);
                call.registerOutParameter(10, ORACLE_CURSOR);
                call.execute();
                result.setOutErrlvl(call.getBigDecimal(9));
                resultSets.add(toRowSet((ResultSet)call.getObject(10)));
            } finally {
                call.close();
            }
        } else {
            CallableStatement call = conn.prepareCall("{call RECA.PKG_CAJA_SERVICES_TRX.CONSULTA_DEUDA_CAJA_RS(?,?,?,?,?,?,?,?,?)}");
            try {
                call.setBigDecimal(1, inClienteTipo);
                call.setBigDecimal(2, inRutRol);
                call.setString(3, inRutRolDv);
                call.setBigDecimal(4, inFormCod);
                call.setString(5, inFormVer);
                call.setBigDecimal(6, inFormFolio);
                call.setTimestamp(7, toTimestamp(inFechaVcto));
                call.setTimestamp(8, toTimestamp(inPeriodo));
                call.registerOutParameter(9, Types.NUMERIC);
                int updateCount = 0;
                boolean haveRset = call.execute();
                while (haveRset || updateCount != -1) {
                    if (!haveRset)
                        updateCount = call.getUpdateCount();
                    else
                        resultSets.add(toRowSet(call.getResultSet()));
                    haveRset = call.getMoreResults();
                }
                result.setOutErrlvl(call.getBigDecimal(9));
            } finally {
                call.close();
            }
        }
        if (resultSets.size() > 0) {
            RowSet[] rowSets = new RowSet[resultSets.size()];
            result.setRowSets((RowSet[]) resultSets.toArray(rowSets));
        }
        return result;
    }
}
