/*
 * Source: PkgCajaServicesTrxException.java - Generated by OBCOM SQL Wizard 5.1.266
 * Author: Felipe Gonzalez M (DP S.A.)
 *
 * Copyright (c) OBCOM INGENIERIA S.A. (Chile). All rights reserved.
 *
 * All rights to this product are owned by OBCOM INGENIERIA S.A. and may only be
 * used  under  the  terms of its associated license document. You may NOT copy,
 * modify, sublicense, or distribute this source file or portions of  it  unless
 * previously  authorized in writing by OBCOM INGENIERIA S.A. In any event, this
 * notice and above copyright must always be included verbatim with this file.
 */

package cl.teso.reca.pkgcajaservicestrx;

/**
 * Exception thrown when the execution of a procedure fails.
 */
public class PkgCajaServicesTrxException extends Exception
{
    private static final long serialVersionUID = 1L;

    /**
     * Create a new PkgCajaServicesTrxException.
     */
    public PkgCajaServicesTrxException()
    {
        super();
    }

    /**
     * Create a new PkgCajaServicesTrxException with supplied message.
     */
    public PkgCajaServicesTrxException(String message)
    {
        super(message);
    }

    /**
     * Create a new PkgCajaServicesTrxException with supplied cause.
     */
    public PkgCajaServicesTrxException(Throwable cause)
    {
        super(cause);
    }

    /**
     * Create a new PkgCajaServicesTrxException with supplied message and cause.
     */
    public PkgCajaServicesTrxException(String message, Throwable cause)
    {
        super(message, cause);
    }
}
