/*
 * Source: ProcedureCaller.java - Generated by OBCOM SQL Wizard 5.1.266
 * Author: Felipe Gonzalez M (DP S.A.)
 *
 * Copyright (c) OBCOM INGENIERIA S.A. (Chile). All rights reserved.
 *
 * All rights to this product are owned by OBCOM INGENIERIA S.A. and may only be
 * used  under  the  terms of its associated license document. You may NOT copy,
 * modify, sublicense, or distribute this source file or portions of  it  unless
 * previously  authorized in writing by OBCOM INGENIERIA S.A. In any event, this
 * notice and above copyright must always be included verbatim with this file.
 */

package cl.teso.reca.pkgcajaservicestrx;

import java.math.BigDecimal;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Timestamp;
import java.util.Date;
import javax.sql.RowSet;
//import weblogic.jdbc.rowset.RowSetFactory;
//import weblogic.jdbc.rowset.WLCachedRowSet;

/**
 * Implements methods common to all procedure callers.
 */
public abstract class ProcedureCaller
{
    // The same as oracle.jdbc.OracleTypes.CURSOR
    protected static final int ORACLE_CURSOR = -10;

    //--------------------------------------------------------------------------
    //-- ResultSet methods -----------------------------------------------------
    //--------------------------------------------------------------------------

    /**
     * Builds a RowSet from the supplied ResultSet.
     */
    protected static RowSet toRowSet(ResultSet resultSet)
        throws SQLException
    {
		return null;
//        RowSetFactory factory = RowSetFactory.newInstance();
//        WLCachedRowSet rowSet = factory.newCachedRowSet();
//        rowSet.populate(resultSet);
//        return rowSet;
    }

    //--------------------------------------------------------------------------
    //-- DATE/TIME conversion methods ------------------------------------------
    //--------------------------------------------------------------------------

    /**
     * Converts the supplied Date to a SQL Timestamp instance.
     */
    protected static Timestamp toTimestamp(Date date)
    {
        if (date == null || date instanceof Timestamp)
            return (Timestamp)date;
        return new Timestamp(date.getTime());
    }

    //--------------------------------------------------------------------------
    //-- Utility methods -------------------------------------------------------
    //--------------------------------------------------------------------------

    /**
     * Returns the supplied string truncated to a maximum length.
     */
    private static String truncate(String value, int maxlen)
    {
        if (value != null && value.length() > maxlen)
            value = value.substring(0, maxlen);
        return value;
    }

    //--------------------------------------------------------------------------
    //-- TRN_AVISO_RECIBO_LIST conversion methods ------------------------------
    //--------------------------------------------------------------------------

    /**
     * Converts an SQL Array to an array of TrnAvisoReciboRowtype.
     */
    protected static TrnAvisoReciboRowtype[] toTrnAvisoReciboList(Object datum)
        throws java.sql.SQLException
    {
        // If datum is null then done
        if (datum == null) return null;

        // Check datum and obtain Array interface
        if (!(datum instanceof java.sql.Array))
            throw new IllegalArgumentException("datum is not an Array");
        java.sql.Array array = (java.sql.Array)datum;

        // Create array of items from Array objects 
        Object[] objects = (Object[])array.getArray();
        TrnAvisoReciboRowtype[] items = new TrnAvisoReciboRowtype[objects.length];

        // Convert Struct objects to TrnAvisoReciboRowtype items
        for (int i = 0; i < objects.length; i++)
            items[i] = toTrnAvisoReciboRowtype(objects[i]);

        // Return items
        return items;
    }

    /**
     * Converts an array of TrnAvisoReciboRowtype to an SQL Array.
     */
    protected static Object dbTrnAvisoReciboList(TrnAvisoReciboRowtype[] items, Connection conn)
        throws java.sql.SQLException
    {
        // If items is null then done
        if (items == null) return null;

        // Convert TrnAvisoReciboRowtype items to SQL Structs
        Object[] objects = new Object[items.length];
        for (int i = 0; i < items.length; i++)
            objects[i] = dbTrnAvisoReciboRowtype(items[i], conn);

        // Create an SQL Array from array of objects
        oracle.sql.ArrayDescriptor descriptor =
            oracle.sql.ArrayDescriptor.createDescriptor("TRN_AVISO_RECIBO_LIST", conn);
        return new oracle.sql.ARRAY(descriptor, conn, objects);
    }

    //--------------------------------------------------------------------------
    //-- TBL_CHAR_T conversion methods -----------------------------------------
    //--------------------------------------------------------------------------

    /**
     * Converts an SQL Array to an array of String.
     */
    protected static String[] toTblChar(Object datum)
        throws java.sql.SQLException
    {
        // If datum is null then done
        if (datum == null) return null;

        // Check datum and obtain Array interface
        if (!(datum instanceof java.sql.Array))
            throw new IllegalArgumentException("datum is not an Array");
        java.sql.Array array = (java.sql.Array)datum;

        // Return array of String
        return (String[])array.getArray();
    }

    /**
     * Converts an array of String to an SQL Array.
     */
    protected static Object dbTblChar(String[] items, Connection conn)
        throws java.sql.SQLException
    {
        // If items is null then done
        if (items == null) return null;

        // Create an SQL Array from array of objects
        oracle.sql.ArrayDescriptor descriptor =
            oracle.sql.ArrayDescriptor.createDescriptor("TBL_CHAR_T", conn);
        return new oracle.sql.ARRAY(descriptor, conn, items);
    }

    //--------------------------------------------------------------------------
    //-- TBL_NUM_T conversion methods ------------------------------------------
    //--------------------------------------------------------------------------

    /**
     * Converts an SQL Array to an array of BigDecimal.
     */
    protected static BigDecimal[] toTblNum(Object datum)
        throws java.sql.SQLException
    {
        // If datum is null then done
        if (datum == null) return null;

        // Check datum and obtain Array interface
        if (!(datum instanceof java.sql.Array))
            throw new IllegalArgumentException("datum is not an Array");
        java.sql.Array array = (java.sql.Array)datum;

        // Return array of BigDecimal
        return (BigDecimal[])array.getArray();
    }

    /**
     * Converts an array of BigDecimal to an SQL Array.
     */
    protected static Object dbTblNum(BigDecimal[] items, Connection conn)
        throws java.sql.SQLException
    {
        // If items is null then done
        if (items == null) return null;

        // Create an SQL Array from array of objects
        oracle.sql.ArrayDescriptor descriptor =
            oracle.sql.ArrayDescriptor.createDescriptor("TBL_NUM_T", conn);
        return new oracle.sql.ARRAY(descriptor, conn, items);
    }

    //--------------------------------------------------------------------------
    //-- TRN_AVISO_RECIBO_ROWTYPE conversion methods ---------------------------
    //--------------------------------------------------------------------------

    /**
     * Converts an SQL Struct to an instance of TrnAvisoReciboRowtype.
     */
    protected static TrnAvisoReciboRowtype toTrnAvisoReciboRowtype(Object datum)
        throws java.sql.SQLException
    {
        // If datum is null then done
        if (datum == null) return null;

        // Check datum and obtain Struct interface
        if (!(datum instanceof java.sql.Struct))
            throw new IllegalArgumentException("datum is not a Struct");
        java.sql.Struct struct = (java.sql.Struct)datum;

        // Obtain Struct attributes and check size
        Object[] attributes = struct.getAttributes();
        if (attributes == null || attributes.length != 26)
            throw new IllegalArgumentException("invalid Struct attributes");

        // Create TrnAvisoReciboRowtype from Struct attributes
        TrnAvisoReciboRowtype result = new TrnAvisoReciboRowtype();
        result.setId((BigDecimal)attributes[0]);
        result.setFolio((BigDecimal)attributes[1]);
        result.setFechaCaja((Date)attributes[2]);
        result.setFechaEmision((Date)attributes[3]);
        result.setFechaValidez((Date)attributes[4]);
        result.setSistema((BigDecimal)attributes[5]);
        result.setUsuario((String)attributes[6]);
        result.setClienteTipo((BigDecimal)attributes[7]);
        result.setRutRol((BigDecimal)attributes[8]);
        result.setRutRolDv((String)attributes[9]);
        result.setFormCod((BigDecimal)attributes[10]);
        result.setFormVer((String)attributes[11]);
        result.setFormFolio((BigDecimal)attributes[12]);
        result.setFormFolioDv((String)attributes[13]);
        result.setPeriodo((Date)attributes[14]);
        result.setFechaVcto((Date)attributes[15]);
        result.setItems((String)attributes[16]);
        result.setItemsCut((String)attributes[17]);
        result.setMoneda((BigDecimal)attributes[18]);
        result.setMontoPlazo((BigDecimal)attributes[19]);
        result.setMontoTotal((BigDecimal)attributes[20]);
        result.setReajustes((BigDecimal)attributes[21]);
        result.setIntereses((BigDecimal)attributes[22]);
        result.setMultas((BigDecimal)attributes[23]);
        result.setCondonaciones((BigDecimal)attributes[24]);
        result.setCodigoBarra((String)attributes[25]);
        return result;
    }

    /**
     * Converts an instance of TrnAvisoReciboRowtype to an SQL Struct.
     */
    protected static Object dbTrnAvisoReciboRowtype(TrnAvisoReciboRowtype item, Connection conn)
        throws java.sql.SQLException
    {
        // If item is null then done
        if (item == null) return null;

        // Create array of Struct attributes
        Object[] attributes = new Object[26];
        attributes[0] = item.getId();
        attributes[1] = item.getFolio();
        attributes[2] = toTimestamp(item.getFechaCaja());
        attributes[3] = toTimestamp(item.getFechaEmision());
        attributes[4] = toTimestamp(item.getFechaValidez());
        attributes[5] = item.getSistema();
        attributes[6] = truncate(item.getUsuario(), 15);
        attributes[7] = item.getClienteTipo();
        attributes[8] = item.getRutRol();
        attributes[9] = truncate(item.getRutRolDv(), 1);
        attributes[10] = item.getFormCod();
        attributes[11] = truncate(item.getFormVer(), 1);
        attributes[12] = item.getFormFolio();
        attributes[13] = truncate(item.getFormFolioDv(), 1);
        attributes[14] = toTimestamp(item.getPeriodo());
        attributes[15] = toTimestamp(item.getFechaVcto());
        attributes[16] = truncate(item.getItems(), 4000);
        attributes[17] = truncate(item.getItemsCut(), 4000);
        attributes[18] = item.getMoneda();
        attributes[19] = item.getMontoPlazo();
        attributes[20] = item.getMontoTotal();
        attributes[21] = item.getReajustes();
        attributes[22] = item.getIntereses();
        attributes[23] = item.getMultas();
        attributes[24] = item.getCondonaciones();
        attributes[25] = truncate(item.getCodigoBarra(), 4000);

        // Create an SQL Struct from array of attributes
        oracle.sql.StructDescriptor descriptor =
            oracle.sql.StructDescriptor.createDescriptor("TRN_AVISO_RECIBO_ROWTYPE", conn);
        return new oracle.sql.STRUCT(descriptor, conn, attributes);
    }
}
