/*
 * Source: TrnAvisoReciboRowtype.java - Generated by OBCOM SQL Wizard 5.1.266
 * Author: Felipe Gonzalez M (DP S.A.)
 *
 * Copyright (c) OBCOM INGENIERIA S.A. (Chile). All rights reserved.
 *
 * All rights to this product are owned by OBCOM INGENIERIA S.A. and may only be
 * used  under  the  terms of its associated license document. You may NOT copy,
 * modify, sublicense, or distribute this source file or portions of  it  unless
 * previously  authorized in writing by OBCOM INGENIERIA S.A. In any event, this
 * notice and above copyright must always be included verbatim with this file.
 */

package cl.teso.reca.pkgcajaservicestrx;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 * Implements the "TRN_AVISO_RECIBO_ROWTYPE" user-defined object.
 */
public class TrnAvisoReciboRowtype implements Serializable
{
    private static final long serialVersionUID = 1L;

    // Fields of the user-defined object
    private BigDecimal  id;               // NUMBER(12)
    private BigDecimal  folio;            // NUMBER(12)
    private Date        fechaCaja;        // DATE
    private Date        fechaEmision;     // DATE
    private Date        fechaValidez;     // DATE
    private BigDecimal  sistema;          // NUMBER(4)
    private String      usuario;          // VARCHAR2(15)
    private BigDecimal  clienteTipo;      // NUMBER(4)
    private BigDecimal  rutRol;           // NUMBER(14)
    private String      rutRolDv;         // CHAR(1)
    private BigDecimal  formCod;          // NUMBER(4)
    private String      formVer;          // CHAR(1)
    private BigDecimal  formFolio;        // NUMBER(12)
    private String      formFolioDv;      // CHAR(1)
    private Date        periodo;          // DATE
    private Date        fechaVcto;        // DATE
    private String      items;            // VARCHAR2(4000)
    private String      itemsCut;         // VARCHAR2(4000)
    private BigDecimal  moneda;           // NUMBER(4)
    private BigDecimal  montoPlazo;       // NUMBER(19,4)
    private BigDecimal  montoTotal;       // NUMBER(19,4)
    private BigDecimal  reajustes;        // NUMBER(19,4)
    private BigDecimal  intereses;        // NUMBER(19,4)
    private BigDecimal  multas;           // NUMBER(19,4)
    private BigDecimal  condonaciones;    // NUMBER(19,4)
    private String      codigoBarra;      // VARCHAR2(4000)

    /**
     * Constructor.
     */
    public TrnAvisoReciboRowtype()
    {
    }

    /**
     * Gets the ID value of this TrnAvisoReciboRowtype.
     */
    public BigDecimal getId()
    {
        return id;
    }

    /**
     * Sets the ID value of this TrnAvisoReciboRowtype.
     */
    public void setId(BigDecimal id)
    {
        this.id = id;
    }

    /**
     * Gets the FOLIO value of this TrnAvisoReciboRowtype.
     */
    public BigDecimal getFolio()
    {
        return folio;
    }

    /**
     * Sets the FOLIO value of this TrnAvisoReciboRowtype.
     */
    public void setFolio(BigDecimal folio)
    {
        this.folio = folio;
    }

    /**
     * Gets the FECHA_CAJA value of this TrnAvisoReciboRowtype.
     */
    public Date getFechaCaja()
    {
        return fechaCaja;
    }

    /**
     * Sets the FECHA_CAJA value of this TrnAvisoReciboRowtype.
     */
    public void setFechaCaja(Date fechaCaja)
    {
        this.fechaCaja = fechaCaja;
    }

    /**
     * Gets the FECHA_EMISION value of this TrnAvisoReciboRowtype.
     */
    public Date getFechaEmision()
    {
        return fechaEmision;
    }

    /**
     * Sets the FECHA_EMISION value of this TrnAvisoReciboRowtype.
     */
    public void setFechaEmision(Date fechaEmision)
    {
        this.fechaEmision = fechaEmision;
    }

    /**
     * Gets the FECHA_VALIDEZ value of this TrnAvisoReciboRowtype.
     */
    public Date getFechaValidez()
    {
        return fechaValidez;
    }

    /**
     * Sets the FECHA_VALIDEZ value of this TrnAvisoReciboRowtype.
     */
    public void setFechaValidez(Date fechaValidez)
    {
        this.fechaValidez = fechaValidez;
    }

    /**
     * Gets the SISTEMA value of this TrnAvisoReciboRowtype.
     */
    public BigDecimal getSistema()
    {
        return sistema;
    }

    /**
     * Sets the SISTEMA value of this TrnAvisoReciboRowtype.
     */
    public void setSistema(BigDecimal sistema)
    {
        this.sistema = sistema;
    }

    /**
     * Gets the USUARIO value of this TrnAvisoReciboRowtype.
     */
    public String getUsuario()
    {
        return usuario;
    }

    /**
     * Sets the USUARIO value of this TrnAvisoReciboRowtype.
     */
    public void setUsuario(String usuario)
    {
        this.usuario = usuario;
    }

    /**
     * Gets the CLIENTE_TIPO value of this TrnAvisoReciboRowtype.
     */
    public BigDecimal getClienteTipo()
    {
        return clienteTipo;
    }

    /**
     * Sets the CLIENTE_TIPO value of this TrnAvisoReciboRowtype.
     */
    public void setClienteTipo(BigDecimal clienteTipo)
    {
        this.clienteTipo = clienteTipo;
    }

    /**
     * Gets the RUT_ROL value of this TrnAvisoReciboRowtype.
     */
    public BigDecimal getRutRol()
    {
        return rutRol;
    }

    /**
     * Sets the RUT_ROL value of this TrnAvisoReciboRowtype.
     */
    public void setRutRol(BigDecimal rutRol)
    {
        this.rutRol = rutRol;
    }

    /**
     * Gets the RUT_ROL_DV value of this TrnAvisoReciboRowtype.
     */
    public String getRutRolDv()
    {
        return rutRolDv;
    }

    /**
     * Sets the RUT_ROL_DV value of this TrnAvisoReciboRowtype.
     */
    public void setRutRolDv(String rutRolDv)
    {
        this.rutRolDv = rutRolDv;
    }

    /**
     * Gets the FORM_COD value of this TrnAvisoReciboRowtype.
     */
    public BigDecimal getFormCod()
    {
        return formCod;
    }

    /**
     * Sets the FORM_COD value of this TrnAvisoReciboRowtype.
     */
    public void setFormCod(BigDecimal formCod)
    {
        this.formCod = formCod;
    }

    /**
     * Gets the FORM_VER value of this TrnAvisoReciboRowtype.
     */
    public String getFormVer()
    {
        return formVer;
    }

    /**
     * Sets the FORM_VER value of this TrnAvisoReciboRowtype.
     */
    public void setFormVer(String formVer)
    {
        this.formVer = formVer;
    }

    /**
     * Gets the FORM_FOLIO value of this TrnAvisoReciboRowtype.
     */
    public BigDecimal getFormFolio()
    {
        return formFolio;
    }

    /**
     * Sets the FORM_FOLIO value of this TrnAvisoReciboRowtype.
     */
    public void setFormFolio(BigDecimal formFolio)
    {
        this.formFolio = formFolio;
    }

    /**
     * Gets the FORM_FOLIO_DV value of this TrnAvisoReciboRowtype.
     */
    public String getFormFolioDv()
    {
        return formFolioDv;
    }

    /**
     * Sets the FORM_FOLIO_DV value of this TrnAvisoReciboRowtype.
     */
    public void setFormFolioDv(String formFolioDv)
    {
        this.formFolioDv = formFolioDv;
    }

    /**
     * Gets the PERIODO value of this TrnAvisoReciboRowtype.
     */
    public Date getPeriodo()
    {
        return periodo;
    }

    /**
     * Sets the PERIODO value of this TrnAvisoReciboRowtype.
     */
    public void setPeriodo(Date periodo)
    {
        this.periodo = periodo;
    }

    /**
     * Gets the FECHA_VCTO value of this TrnAvisoReciboRowtype.
     */
    public Date getFechaVcto()
    {
        return fechaVcto;
    }

    /**
     * Sets the FECHA_VCTO value of this TrnAvisoReciboRowtype.
     */
    public void setFechaVcto(Date fechaVcto)
    {
        this.fechaVcto = fechaVcto;
    }

    /**
     * Gets the ITEMS value of this TrnAvisoReciboRowtype.
     */
    public String getItems()
    {
        return items;
    }

    /**
     * Sets the ITEMS value of this TrnAvisoReciboRowtype.
     */
    public void setItems(String items)
    {
        this.items = items;
    }

    /**
     * Gets the ITEMS_CUT value of this TrnAvisoReciboRowtype.
     */
    public String getItemsCut()
    {
        return itemsCut;
    }

    /**
     * Sets the ITEMS_CUT value of this TrnAvisoReciboRowtype.
     */
    public void setItemsCut(String itemsCut)
    {
        this.itemsCut = itemsCut;
    }

    /**
     * Gets the MONEDA value of this TrnAvisoReciboRowtype.
     */
    public BigDecimal getMoneda()
    {
        return moneda;
    }

    /**
     * Sets the MONEDA value of this TrnAvisoReciboRowtype.
     */
    public void setMoneda(BigDecimal moneda)
    {
        this.moneda = moneda;
    }

    /**
     * Gets the MONTO_PLAZO value of this TrnAvisoReciboRowtype.
     */
    public BigDecimal getMontoPlazo()
    {
        return montoPlazo;
    }

    /**
     * Sets the MONTO_PLAZO value of this TrnAvisoReciboRowtype.
     */
    public void setMontoPlazo(BigDecimal montoPlazo)
    {
        this.montoPlazo = montoPlazo;
    }

    /**
     * Gets the MONTO_TOTAL value of this TrnAvisoReciboRowtype.
     */
    public BigDecimal getMontoTotal()
    {
        return montoTotal;
    }

    /**
     * Sets the MONTO_TOTAL value of this TrnAvisoReciboRowtype.
     */
    public void setMontoTotal(BigDecimal montoTotal)
    {
        this.montoTotal = montoTotal;
    }

    /**
     * Gets the REAJUSTES value of this TrnAvisoReciboRowtype.
     */
    public BigDecimal getReajustes()
    {
        return reajustes;
    }

    /**
     * Sets the REAJUSTES value of this TrnAvisoReciboRowtype.
     */
    public void setReajustes(BigDecimal reajustes)
    {
        this.reajustes = reajustes;
    }

    /**
     * Gets the INTERESES value of this TrnAvisoReciboRowtype.
     */
    public BigDecimal getIntereses()
    {
        return intereses;
    }

    /**
     * Sets the INTERESES value of this TrnAvisoReciboRowtype.
     */
    public void setIntereses(BigDecimal intereses)
    {
        this.intereses = intereses;
    }

    /**
     * Gets the MULTAS value of this TrnAvisoReciboRowtype.
     */
    public BigDecimal getMultas()
    {
        return multas;
    }

    /**
     * Sets the MULTAS value of this TrnAvisoReciboRowtype.
     */
    public void setMultas(BigDecimal multas)
    {
        this.multas = multas;
    }

    /**
     * Gets the CONDONACIONES value of this TrnAvisoReciboRowtype.
     */
    public BigDecimal getCondonaciones()
    {
        return condonaciones;
    }

    /**
     * Sets the CONDONACIONES value of this TrnAvisoReciboRowtype.
     */
    public void setCondonaciones(BigDecimal condonaciones)
    {
        this.condonaciones = condonaciones;
    }

    /**
     * Gets the CODIGO_BARRA value of this TrnAvisoReciboRowtype.
     */
    public String getCodigoBarra()
    {
        return codigoBarra;
    }

    /**
     * Sets the CODIGO_BARRA value of this TrnAvisoReciboRowtype.
     */
    public void setCodigoBarra(String codigoBarra)
    {
        this.codigoBarra = codigoBarra;
    }
}
