/*
 * File: FormPagoCajaCaller.java  2009-09-10 15:52:14-04:00
 * User: Felipe Gonzalez (DP S.A.)
 *
 * File generated by OBCOM SQL Wizard 5.1.248 (www.obcom.cl).
 * DO NOT EDIT THIS FILE <<Signature:g0CH+cgJIlXlMflb9kKPjO>>.
 */

package cl.teso.reca.cajasrv.pkgcajaservices;

import java.math.BigDecimal;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Types;
import java.util.ArrayList;
import javax.sql.DataSource;
import javax.sql.RowSet;

/**
 * Implements a caller of procedure "RECA.PKG_CAJA_SERVICES.FORM_PAGO_CAJA".
 *
 * RETURN_VALUE       NUMBER             Return
 * IN_FRM_ID          NUMBER             Input
 */
public class FormPagoCajaCaller extends ProcedureCaller
{
    /**
     * Executes procedure "RECA.PKG_CAJA_SERVICES.FORM_PAGO_CAJA" using a DataSource.
     */
    public static FormPagoCajaResult execute(DataSource dataSource, BigDecimal inFrmId)
        throws SQLException
    {
        Connection conn = dataSource.getConnection();
        try
        {
            return execute(conn, inFrmId);
        }
        finally
        {
            conn.close();
        }
    }

    /**
     * Executes procedure "RECA.PKG_CAJA_SERVICES.FORM_PAGO_CAJA" using a Connection.
     */
    public static FormPagoCajaResult execute(Connection conn, BigDecimal inFrmId)
        throws SQLException
    {
        FormPagoCajaResult result = new FormPagoCajaResult();
        ArrayList resultSets = new ArrayList();
        CallableStatement call = conn.prepareCall("{?=call RECA.PKG_CAJA_SERVICES.FORM_PAGO_CAJA(?)}");
        try
        {
            call.registerOutParameter(1, Types.NUMERIC);
            call.setBigDecimal(2, inFrmId);
            int updateCount = 0;
            boolean haveRset = call.execute();
            while (haveRset || updateCount != -1)
            {
                if (!haveRset)
                    updateCount = call.getUpdateCount();
                else
                    resultSets.add(toRowSet(call.getResultSet()));
                haveRset = call.getMoreResults();
            }
            result.setReturnValue(call.getBigDecimal(1));
        }
        finally
        {
            call.close();
        }
        if (resultSets.size() > 0)
        {
            RowSet[] rowSets = new RowSet[resultSets.size()];
            result.setRowSets((RowSet[]) resultSets.toArray(rowSets));
        }
        return result;
    }
}
