/*
 * File: IngresarPagoCaller.java  2009-09-10 15:52:15-04:00
 * User: Felipe Gonzalez (DP S.A.)
 *
 * File generated by OBCOM SQL Wizard 5.1.248 (www.obcom.cl).
 * DO NOT EDIT THIS FILE <<Signature:CCQojAKhyNQwhEnsaerAnM>>.
 */

package cl.teso.reca.cajasrv.pkgcajaservices;

import java.math.BigDecimal;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Types;
import java.util.ArrayList;
import java.util.Date;
import javax.sql.DataSource;
import javax.sql.RowSet;

/**
 * Implements a caller of procedure "RECA.PKG_CAJA_SERVICES.INGRESAR_PAGO".
 *
 * IN_DPSID           NUMBER             Input
 * IN_ID_PAGO         VARCHAR2(4000)     Input
 * IN_MONTO_PAGADO    NUMBER             Input
 * IN_FECHA_PAGO      DATE               Input
 * OUT_RESULT_CODE    NUMBER             Output
 */
public class IngresarPagoCaller extends ProcedureCaller
{
    /**
     * Executes procedure "RECA.PKG_CAJA_SERVICES.INGRESAR_PAGO" using a DataSource.
     */
    public static IngresarPagoResult execute(DataSource dataSource, BigDecimal inDpsid, String inIdPago, BigDecimal inMontoPagado, Date inFechaPago)
        throws SQLException
    {
        Connection conn = dataSource.getConnection();
        try
        {
            return execute(conn, inDpsid, inIdPago, inMontoPagado, inFechaPago);
        }
        finally
        {
            conn.close();
        }
    }

    /**
     * Executes procedure "RECA.PKG_CAJA_SERVICES.INGRESAR_PAGO" using a Connection.
     */
    public static IngresarPagoResult execute(Connection conn, BigDecimal inDpsid, String inIdPago, BigDecimal inMontoPagado, Date inFechaPago)
        throws SQLException
    {
        IngresarPagoResult result = new IngresarPagoResult();
        ArrayList resultSets = new ArrayList();
        CallableStatement call = conn.prepareCall("{call RECA.PKG_CAJA_SERVICES.INGRESAR_PAGO(?,?,?,?,?)}");
        try
        {
            call.setBigDecimal(1, inDpsid);
            call.setString(2, inIdPago);
            call.setBigDecimal(3, inMontoPagado);
            call.setTimestamp(4, toTimestamp(inFechaPago));
            call.registerOutParameter(5, Types.NUMERIC);
            int updateCount = 0;
            boolean haveRset = call.execute();
            while (haveRset || updateCount != -1)
            {
                if (!haveRset)
                    updateCount = call.getUpdateCount();
                else
                    resultSets.add(toRowSet(call.getResultSet()));
                haveRset = call.getMoreResults();
            }
            result.setOutResultCode(call.getBigDecimal(5));
        }
        finally
        {
            call.close();
        }
        if (resultSets.size() > 0)
        {
            RowSet[] rowSets = new RowSet[resultSets.size()];
            result.setRowSets((RowSet[]) resultSets.toArray(rowSets));
        }
        return result;
    }
}
