/*
 * @(#)GrabaLogTransaccionResult.java  2006/11/22 17:30:44
 *
 * This file was generated by "OBCOM SQL Wizard" version 5.1.198.
 * Copyright (c) OBCOM INGENIERIA S.A. (Chile) All rights reserved.
 * OBCOM PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 *
 * DO NOT EDIT THIS FILE <<Signature:jPD4uMSnFMKA+06NX5qx3n>>.
 */

package cl.teso.reca.pkgcajaserviceslog;

import java.math.BigDecimal;

/**
 * Output parameters of procedure "RECA.PKG_CAJA_SERVICES_LOG.GRABA_LOG_TRANSACCION".
 */
public class GrabaLogTransaccionResult implements java.io.Serializable
{
    private static final long serialVersionUID = 1L;
    private BigDecimal myOutResultCode;

    /**
     * Create a new GrabaLogTransaccionResult.
     */
    public GrabaLogTransaccionResult() {}

    /**
     * Gets the OutResultCode value of this GrabaLogTransaccionResult.
     */
    public BigDecimal getOutResultCode()
    {
        return myOutResultCode;
    }

    /**
     * Sets the OutResultCode value of this GrabaLogTransaccionResult.
     */
    public void setOutResultCode(BigDecimal value)
    {
        myOutResultCode = value;
    }
}
