/*
 * @(#)PkgCajaServicesLogException.java  2006/11/22 17:30:44
 *
 * This file was generated by "OBCOM SQL Wizard" version 5.1.198.
 * Copyright (c) OBCOM INGENIERIA S.A. (Chile) All rights reserved.
 * OBCOM PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 *
 * DO NOT EDIT THIS FILE <<Signature:3T22xxNeXXSrgx7VCqTU-x>>.
 */

package cl.teso.reca.pkgcajaserviceslog;

/**
 * Exception thrown when the execution of a procedure fails.
 */
public class PkgCajaServicesLogException extends java.lang.Exception
{
    private static final long serialVersionUID = 1L;

    /**
     * Create a new PkgCajaServicesLogException with supplied procedure name and cause.
     */
    public PkgCajaServicesLogException(String procedure, Throwable cause)
    {
        super("Execution of procedure "+procedure+" failed", cause);
    }
}
